"""Diagnostics FastAPI routes."""

from __future__ import annotations

import datetime
import json
import os
import zipfile

from fastapi import Request


def register_diagnostics_routes(app, ctx) -> None:
    @app.api_route("/api/diagnostics/run", methods=["GET", "POST"])
    async def diagnostics_run(request: Request):
        if error := ctx.auth_error(request):
            return error
        return ctx.fastapi_json(ctx.build_diagnostics_payload())

    @app.api_route("/api/diagnostics/prerequisites", methods=["GET", "POST"])
    async def diagnostics_prerequisites(request: Request):
        if error := ctx.auth_error(request):
            return error
        return ctx.fastapi_json(ctx.build_prerequisite_diagnostics_payload())

    def _truthy(value: object) -> bool:
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            return value.strip().lower() in {"1", "true", "yes", "on"}
        return False

    @app.post("/api/diagnostics/repair")
    async def diagnostics_repair(request: Request):
        if error := ctx.auth_error(request):
            return error
        body = await ctx.body(request)
        if not _truthy(body.get("confirmed")):
            return ctx.fastapi_json({"error": "环境修复需要确认"}, 403)
        if body.get("scope") == "prerequisites":
            result = ctx.get_process_svc().repair_prerequisites()
            result["diagnostics"] = ctx.finalize_prerequisite_diagnostics(result.get("diagnostics", {}))
        else:
            result = ctx.get_process_svc().repair_environment()
            result["diagnostics"] = ctx.append_runtime_checks(result.get("diagnostics", {}))
        return ctx.fastapi_json(result)

    @app.api_route("/api/diagnostics/export", methods=["GET", "POST"])
    async def diagnostics_export(request: Request):
        if error := ctx.auth_error(request):
            return error

        diagnostics = ctx.build_diagnostics_payload()
        now = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        export_dir = os.path.join(ctx.paths.data_dir, "diagnostics")
        os.makedirs(export_dir, exist_ok=True)
        filename = f"openclaw-diagnostics-{now}.zip"
        zip_path = os.path.join(export_dir, filename)

        system_info = {
            "generatedAt": datetime.datetime.now().isoformat(timespec="seconds"),
            "basePath": ctx.paths.base_path,
            "nodePath": ctx.paths.node_exe,
            "openclawMjs": ctx.paths.openclaw_mjs,
            "stateDir": ctx.paths.state_dir,
            "diagnosticSummary": diagnostics.get("summary", {}),
        }

        with ctx.log_lock:
            service_log = ctx.sanitize_text("".join(ctx.log_buffer))

        readme = (
            "OpenClaw diagnostics package\n\n"
            "This package is generated by the launcher for troubleshooting.\n"
            "Secrets such as API keys, tokens, passwords, signatures and app secrets are masked.\n"
        )

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("README.txt", readme)
            archive.writestr("diagnostics.json", json.dumps(diagnostics, ensure_ascii=False, indent=2))
            archive.writestr("system.json", json.dumps(system_info, ensure_ascii=False, indent=2))
            archive.writestr("service.log", service_log)
            persisted_log = os.path.join(ctx.paths.data_dir, "logs", "bridge-service.log")
            startup_snapshot = os.path.join(ctx.paths.data_dir, "logs", "openclaw-startup-snapshot.json")
            if os.path.exists(persisted_log):
                with open(persisted_log, "r", encoding="utf-8", errors="replace") as file:
                    archive.writestr("logs/bridge-service.log", ctx.sanitize_text(file.read()))
            if os.path.exists(startup_snapshot):
                archive.writestr("logs/openclaw-startup-snapshot.json", json.dumps(ctx.read_sanitized_json(startup_snapshot, {}), ensure_ascii=False, indent=2))
            archive.writestr("configs/openclaw.json", json.dumps(ctx.read_sanitized_json(ctx.paths.openclaw_config, {}), ensure_ascii=False, indent=2))
            archive.writestr("configs/runtime-context.json", json.dumps(ctx.read_sanitized_json(os.path.join(ctx.paths.openclaw_workspace, "runtime-context.json"), {}), ensure_ascii=False, indent=2))
            archive.writestr("configs/launcher-runtime.json", json.dumps(ctx.read_sanitized_json(os.path.join(ctx.paths.data_dir, "launcher_runtime.json"), {}), ensure_ascii=False, indent=2))
            archive.writestr("configs/brand-profile.json", json.dumps(ctx.read_sanitized_json(ctx.paths.brand_profile, {}), ensure_ascii=False, indent=2))
            archive.writestr("configs/auth-profiles.json", json.dumps(ctx.read_sanitized_json(ctx.paths.auth_profiles, {}), ensure_ascii=False, indent=2))
            archive.writestr("configs/imgapi_config.json", json.dumps(ctx.read_sanitized_json(ctx.paths.image_config, {}), ensure_ascii=False, indent=2))
            archive.writestr("configs/video_config.json", json.dumps(ctx.read_sanitized_json(ctx.paths.video_config, {}), ensure_ascii=False, indent=2))

        return ctx.fastapi_json({
            "path": zip_path,
            "directory": export_dir,
            "filename": filename,
            "size": os.path.getsize(zip_path),
        })
