import type { BotChannel, BotChannelKey } from './botPluginTypes';

export const CHANNELS: Record<BotChannelKey, BotChannel> = {
  feishu: {
    key: 'feishu',
    configKey: 'feishu',
    legacyConfigKey: 'openclaw-lark',
    title: '飞书机器人',
    description: '安装 OpenClaw 飞书插件，并写入飞书开放平台应用配置。',
    pluginName: 'openclaw-lark',
    packageName: '@larksuite/openclaw-lark',
    packagePaths: [
      'node_modules/@larksuite/openclaw-lark/package.json',
      'SystemData/.core/node_modules/@larksuite/openclaw-lark/package.json',
      'data/.openclaw/extensions/openclaw-lark/package.json',
      'data/.openclaw/extensions/lark/package.json',
    ],
    installSteps: [
      {
        label: '飞书扫码配置',
        displayCommand: 'node scripts/bot-plugin-helper.mjs login-feishu',
        commandName: 'bot-plugin-login-feishu',
        fallbackCommandName: 'bot-plugin-login-feishu-node-exe',
        args: ['scripts/bot-plugin-helper.mjs', 'login-feishu'],
        successMessage: '飞书扫码配置已完成。重启核心服务后生效。',
      },
    ],
    idLabel: 'App ID',
    idPlaceholder: 'cli_xxx',
    secretLabel: 'App Secret',
    secretPlaceholder: '请输入 App Secret',
    docsUrl: 'https://open.feishu.cn/app',
    docsLabel: '打开飞书开放平台',
    manualConfig: true,
  },
  weixin: {
    key: 'weixin',
    configKey: 'openclaw-weixin',
    title: '微信机器人',
    description: '安装 OpenClaw 微信绑定插件。微信绑定只能通过命令行输出中的二维码扫码完成。',
    pluginName: 'openclaw-weixin',
    packageName: '@tencent-weixin/openclaw-weixin',
    packagePaths: [
      'node_modules/@tencent-weixin/openclaw-weixin/package.json',
      'SystemData/.core/node_modules/@tencent-weixin/openclaw-weixin/package.json',
      'data/.openclaw/extensions/openclaw-weixin/package.json',
      'data/.openclaw/extensions/weixin/package.json',
      'data/.openclaw/extensions/wechat/package.json',
    ],
    installSteps: [
      {
        label: '微信扫码绑定',
        displayCommand: 'node scripts/bot-plugin-helper.mjs login-weixin',
        commandName: 'bot-plugin-login-weixin',
        fallbackCommandName: 'bot-plugin-login-weixin-node-exe',
        args: ['scripts/bot-plugin-helper.mjs', 'login-weixin'],
        successMessage: '微信扫码绑定命令已结束。绑定完成后，请重启核心服务生效。',
      },
    ],
    idLabel: '',
    idPlaceholder: '',
    secretLabel: '',
    secretPlaceholder: '',
    manualConfig: false,
  },
  dingtalk: {
    key: 'dingtalk',
    configKey: 'dingtalk-connector',
    title: '钉钉机器人',
    description: '安装钉钉官方 OpenClaw Channel 插件，并通过钉钉扫码授权企业内部机器人。',
    pluginName: 'dingtalk-connector',
    packageName: '@dingtalk-real-ai/dingtalk-connector',
    packagePaths: [
      'node_modules/@dingtalk-real-ai/dingtalk-connector/package.json',
      'SystemData/.core/node_modules/@dingtalk-real-ai/dingtalk-connector/package.json',
      'data/.openclaw/extensions/dingtalk-connector/package.json',
      'data/.openclaw/extensions/dingtalk/package.json',
    ],
    installSteps: [
      {
        label: '钉钉扫码授权',
        displayCommand: 'node scripts/bot-plugin-helper.mjs login-dingtalk',
        commandName: 'bot-plugin-login-dingtalk',
        fallbackCommandName: 'bot-plugin-login-dingtalk-node-exe',
        args: ['scripts/bot-plugin-helper.mjs', 'login-dingtalk'],
        successMessage: '钉钉扫码授权命令已结束。授权完成后，请重启核心服务或 Gateway 生效。',
      },
    ],
    idLabel: '',
    idPlaceholder: '',
    secretLabel: '',
    secretPlaceholder: '',
    docsUrl: 'https://open.dingtalk.com/document/development/open-claw-nail-insertion-plugin',
    docsLabel: '打开钉钉开放平台文档',
    manualConfig: false,
  },
};
