#!/bin/bash
set -euo pipefail

REMOTE_DIR="${LICENSE_REMOTE_DIR:-/opt/openclaw-license}"
SERVICE_NAME="${LICENSE_SERVICE_NAME:-openclaw-license}"
SERVER_UPLOAD="${LICENSE_SERVER_UPLOAD:-/tmp/openclaw-license-server.py}"
ADMIN_HTML_UPLOAD="${LICENSE_ADMIN_HTML_UPLOAD:-/tmp/openclaw-license-admin_console.html}"
RELAY_ENV_FILE="${LICENSE_RELAY_ENV_FILE:-$REMOTE_DIR/openclaw-license.env}"
LOCAL_BASE_URL="${LICENSE_LOCAL_BASE_URL:-http://127.0.0.1:18791}"
RELAY_TOKEN="${OPENCLAW_PUBLISH_RELAY_TOKEN:-${PUBLISH_RELAY_TOKEN:-}}"

echo "======================================"
echo "OpenClaw license server deploy"
echo "======================================"
echo ""

cd "$REMOTE_DIR"

ts="$(date -u +%Y%m%d%H%M%S)"

echo "[1/7] Backup current files"
cp server.py "server.py.bak-$ts"
if [ -f admin_console.html ]; then
  cp admin_console.html "admin_console.html.bak-$ts"
fi
echo "backup=server.py.bak-$ts"
echo ""

echo "[2/7] Validate upload"
if [ ! -f "$SERVER_UPLOAD" ]; then
  echo "missing upload: $SERVER_UPLOAD" >&2
  echo "copy the new server.py to that path or set LICENSE_SERVER_UPLOAD" >&2
  exit 1
fi
sha256sum "$SERVER_UPLOAD"
python3 -m py_compile "$SERVER_UPLOAD"
echo ""

echo "[3/7] Install server files"
install -m 0644 "$SERVER_UPLOAD" "$REMOTE_DIR/server.py"
if [ -f "$ADMIN_HTML_UPLOAD" ]; then
  install -m 0644 "$ADMIN_HTML_UPLOAD" "$REMOTE_DIR/admin_console.html"
else
  echo "admin html upload not found, skipped: $ADMIN_HTML_UPLOAD"
fi
echo ""

echo "[4/7] Configure publish relay environment"
dropin_dir="/etc/systemd/system/${SERVICE_NAME}.service.d"
mkdir -p "$dropin_dir"
cat > "$dropin_dir/publish-relay.conf" <<EOF
[Service]
EnvironmentFile=-$RELAY_ENV_FILE
EOF

if [ -n "$RELAY_TOKEN" ]; then
  export RELAY_ENV_FILE RELAY_TOKEN
  umask 077
  python3 - <<'PY'
import os


def env_line(name, value):
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("`", "\\`")
        .replace("\r", "")
        .replace("\n", "")
    )
    return f'{name}="{escaped}"\n'

with open(os.environ["RELAY_ENV_FILE"], "w", encoding="utf-8") as file:
    file.write("# Generated by deploy.sh.\n")
    file.write(env_line("OPENCLAW_PUBLISH_RELAY_TOKEN", os.environ["RELAY_TOKEN"]))
PY
  chmod 600 "$RELAY_ENV_FILE"
  echo "relay_token=configured"
else
  echo "relay_token=not configured; relay endpoints will remain fail-closed"
fi
systemctl daemon-reload
echo ""

echo "[5/7] Restart service"
systemctl restart "$SERVICE_NAME"
sleep 2
systemctl is-active "$SERVICE_NAME"
echo ""

echo "[6/7] Smoke test"
curl -fsS "$LOCAL_BASE_URL/health"
echo ""
curl -sS -X POST "$LOCAL_BASE_URL/api/member/activate" \
  -H 'Content-Type: application/json' \
  -d '{"code":"INVALID-SMOKE","installId":"smoke","deviceId":"smoke"}'
echo ""
if [ -n "$RELAY_TOKEN" ]; then
  curl -fsS "$LOCAL_BASE_URL/api/lumi/relay/health" \
    -H "Authorization: Bearer $RELAY_TOKEN"
  echo ""
fi
echo ""

echo "[7/7] Key files"
echo "license.db: $( [ -f license.db ] && echo present || echo missing )"
echo "private_key.b64: $( [ -f private_key.b64 ] && echo present || echo missing )"
echo "admin_token.txt: $( [ -f admin_token.txt ] && echo present || echo missing )"
echo "relay env: $( [ -f "$RELAY_ENV_FILE" ] && echo present || echo missing )"
echo ""
echo "======================================"
echo "Deploy complete"
echo "======================================"
